<?php
$classi = [
    "Classe 1A" => [
        [
            "id" => 1,
            "nome" => "Marco",
            "cognome" => "Rossi",
            "anni" => 23,
            "voto_medio" => 8.5,
            "linguaggio_preferito" => "PHP",
            "immagine" => "https://robohash.org/studentmarcorossi",
        ],
        [
            "id" => 2,
            "nome" => "Luca",
            "cognome" => "Verdi",
            "anni" => 27,
            "voto_medio" => 3.5,
            "linguaggio_preferito" => "JS",
            "immagine" => "https://robohash.org/studentlucaverdi",
        ],
        [
            "id" => 3,
            "nome" => "Giulia",
            "cognome" => "Bianchi",
            "anni" => 23,
            "voto_medio" => 5.5,
            "linguaggio_preferito" => "CSS",
            "immagine" => "https://robohash.org/studentgiuliabianchi",
        ],
        [
            "id" => 4,
            "nome" => "Sofia",
            "cognome" => "Russo",
            "anni" => 27,
            "voto_medio" => 8.0,
            "linguaggio_preferito" => "HTML",
            "immagine" => "https://robohash.org/studentsofiarusso",
        ],
        [
            "id" => 5,
            "nome" => "Andrea",
            "cognome" => "Ferrari",
            "anni" => 22,
            "voto_medio" => 7.5,
            "linguaggio_preferito" => "PHP",
            "immagine" => "https://robohash.org/studentandreaferrari",
        ],
    ],
    "Classe 2A" => [
        [
            "id" => 27,
            "nome" => "Francesca",
            "cognome" => "Ricci",
            "anni" => 27,
            "voto_medio" => 9.0,
            "linguaggio_preferito" => "JS",
            "immagine" => "https://robohash.org/studentfrancescaricci",
        ],
        [
            "id" => 22,
            "nome" => "Matteo",
            "cognome" => "Moretti",
            "anni" => 23,
            "voto_medio" => 4.3,
            "linguaggio_preferito" => "HTML",
            "immagine" => "https://robohash.org/studentmatteomoretti",
        ],
        [
            "id" => 30,
            "nome" => "Alessandro",
            "cognome" => "Lombardi",
            "anni" => 27,
            "voto_medio" => 5.4,
            "linguaggio_preferito" => "CSS",
            "immagine" => "https://robohash.org/studentalessandrolombardi",
        ],
        [
            "id" => 33,
            "nome" => "Elena",
            "cognome" => "Conti",
            "anni" => 22,
            "voto_medio" => 8.4,
            "linguaggio_preferito" => "PHP",
            "immagine" => "https://robohash.org/studentelenaconti",
        ],
        [
            "id" => 20,
            "nome" => "Valeria",
            "cognome" => "Gallo",
            "anni" => 27,
            "voto_medio" => 9.5,
            "linguaggio_preferito" => "JS",
            "immagine" => "https://robohash.org/studentvaleriagallo",
        ],
    ],
    "Classe 3A" => [
        [
            "id" => 31,
            "nome" => "Simone",
            "cognome" => "Fabbri",
            "anni" => 22,
            "voto_medio" => 6.9,
            "linguaggio_preferito" => "CSS",
            "immagine" => "https://robohash.org/studentsimonefabbri",
        ],
        [
            "id" => 32,
            "nome" => "Chiara",
            "cognome" => "Riva",
            "anni" => 27,
            "voto_medio" => 5.3,
            "linguaggio_preferito" => "HTML",
            "immagine" => "https://robohash.org/studentchiarariva",
        ],
        [
            "id" => 33,
            "nome" => "Lorenzo",
            "cognome" => "Orlando",
            "anni" => 22,
            "voto_medio" => 8.2,
            "linguaggio_preferito" => "PHP",
            "immagine" => "https://robohash.org/studentlorenzoorlando",
        ],
        [
            "id" => 34,
            "nome" => "Marta",
            "cognome" => "Martini",
            "anni" => 22,
            "voto_medio" => 4.8,
            "linguaggio_preferito" => "JS",
            "immagine" => "https://robohash.org/studentmartamartini",
        ],
        [
            "id" => 35,
            "nome" => "Giovanni",
            "cognome" => "Giuliani",
            "anni" => 27,
            "voto_medio" => 8.1,
            "linguaggio_preferito" => "CSS",
            "immagine" => "https://robohash.org/studentgiovannigiuliani",
        ],
    ],
    "Classe 4A" => [
        [
            "id" => 46,
            "nome" => "Silvia",
            "cognome" => "De Luca",
            "anni" => 30,
            "voto_medio" => 4.2,
            "linguaggio_preferito" => "PHP",
            "immagine" => "https://robohash.org/studentsilviadeluca",
        ],
        [
            "id" => 47,
            "nome" => "Federico",
            "cognome" => "Costa",
            "anni" => 30,
            "voto_medio" => 5.1,
            "linguaggio_preferito" => "HTML",
            "immagine" => "https://robohash.org/studentfedericocosta",
        ],
        [
            "id" => 48,
            "nome" => "Michele",
            "cognome" => "Cattaneo",
            "anni" => 22,
            "voto_medio" => 3.7,
            "linguaggio_preferito" => "JS",
            "immagine" => "https://robohash.org/studentmichelecattaneo",
        ],
        [
            "id" => 49,
            "nome" => "Anna",
            "cognome" => "Serra",
            "anni" => 30,
            "voto_medio" => 8.6,
            "linguaggio_preferito" => "CSS",
            "immagine" => "https://robohash.org/studentannaserra",
        ],
        [
            "id" => 50,
            "nome" => "Antonio",
            "cognome" => "Cervi",
            "anni" => 30,
            "voto_medio" => 4.0,
            "linguaggio_preferito" => "PHP",
            "immagine" => "https://robohash.org/studentantoniocervi",
        ],
    ],
    "Classe 5A" => [
        [
            "id" => 61,
            "nome" => "Davide",
            "cognome" => "Ferrero",
            "anni" => 33,
            "voto_medio" => 8.7,
            "linguaggio_preferito" => "JS",
            "immagine" => "https://robohash.org/studentdaideferrero",
        ],
        [
            "id" => 62,
            "nome" => "Sara",
            "cognome" => "Leoni",
            "anni" => 33,
            "voto_medio" => 4.1,
            "linguaggio_preferito" => "PHP",
            "immagine" => "https://robohash.org/studentsaraleoni",
        ],
        [
            "id" => 63,
            "nome" => "Daniele",
            "cognome" => "Bertoni",
            "anni" => 33,
            "voto_medio" => 4.4,
            "linguaggio_preferito" => "HTML",
            "immagine" => "https://robohash.org/studentdanielebertoni",
        ],
        [
            "id" => 64,
            "nome" => "Giada",
            "cognome" => "Ragusa",
            "anni" => 30,
            "voto_medio" => 5.0,
            "linguaggio_preferito" => "CSS",
            "immagine" => "https://robohash.org/studentgiadaragusa",
        ],
        [
            "id" => 65,
            "nome" => "Claudio",
            "cognome" => "Lanza",
            "anni" => 30,
            "voto_medio" => 6.7,
            "linguaggio_preferito" => "PHP",
            "immagine" => "https://robohash.org/studentclaudiolanza",
        ],
    ],
];
